// <auto-generated />
namespace AWO_Team14.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class votesmodelstuff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(votesmodelstuff));
        
        string IMigrationMetadata.Id
        {
            get { return "201804300235241_votes model stuff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
