using AWO_Team14.Models;
using AWO_Team14.DAL;
using System.Data.Entity.Migrations;
using System;
using System.Linq;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace AWO_Team14.Migrations
{
	public class CustomerData
	{
		public void SeedCustomers(AppDbContext db)

		{
			//create a user manager and a role manager to use for this method
			AppUserManager UserManager = new AppUserManager(new UserStore<AppUser>(db));

			UserManager.PasswordValidator = new PasswordValidator
			{
				RequiredLength = 6,
				RequireNonLetterOrDigit = false,
				RequireDigit = false,
				RequireLowercase = false,
				RequireUppercase = false
			};


			AppUser u1 = new AppUser();
			//u1.CustomerNumber = 5001;
			//u1.Password = "hello1";
			u1.LastName = "Baker";
			u1.FirstName = "Christopher";
			u1.MiddleInitial = "L.";
			u1.Birthday = new DateTime(1949, 11, 23);
			u1.Street = "1245 Lake Anchorage Blvd.";
			u1.City =  "Austin";
			u1.State = State.TX;
			u1.Zip = "78705";
			u1.PhoneNumber  = "5125550180";
			u1.Email = "cbaker@example.com";
			u1.UserName = "cbaker@example.com";
			u1.PopcornPoints = 110;
			var result1 = UserManager.Create(u1, "hello1");
			db.SaveChanges();
			u1 = db.Users.FirstOrDefault(u => u.UserName == "cbaker@example.com");
			UserManager.AddToRole(u1.Id, "Customer");
			db.SaveChanges();

			AppUser u2 = new AppUser();
			//u2.CustomerNumber = 5002;
			//u2.Password = "potato";
			u2.LastName = "Banks";
			u2.FirstName = "Michelle";
			u2.MiddleInitial = "";
			u2.Birthday = new DateTime(1962, 11, 27);
			u2.Street = "1300 Tall Pine Lane";
			u2.City =  "Austin";
			u2.State = State.TX;
			u2.Zip = "78712";
			u2.PhoneNumber  = "5125550183";
			u2.Email = "banker@longhorn.net";
			u1.UserName = "banker@longhorn.net";
			u2.PopcornPoints = 40;
			var result2 = UserManager.Create(u2, "potato");
			db.SaveChanges();
			u2 = db.Users.FirstOrDefault(u => u.UserName == "banker@longhorn.net");
			UserManager.AddToRole(u2.Id, "Customer");
			db.SaveChanges();

			AppUser u3 = new AppUser();
			//u3.CustomerNumber = 5003;
			//u3.Password = "painting";
			u3.LastName = "Broccolo";
			u3.FirstName = "Franco";
			u3.MiddleInitial = "V";
			u3.Birthday = new DateTime(1992, 10, 11);
			u3.Street = "62 Browning Road";
			u3.City =  "Austin";
			u3.State = State.TX;
			u3.Zip = "78704";
			u3.PhoneNumber  = "5125550128";
			u3.Email = "franco@example.com";
			u3.UserName = "franco@example.com";
			u3.PopcornPoints = 30;
			var result3 = UserManager.Create(u3, "painting");
			db.SaveChanges();
			u3 = db.Users.FirstOrDefault(u => u.UserName == "franco@example.com");
			UserManager.AddToRole(u3.Id, "Customer");
			db.SaveChanges();

			AppUser u4 = new AppUser();
			//u4.CustomerNumber = 5004;
			//u4.Password = "texas1";
			u4.LastName = "Chang";
			u4.FirstName = "Wendy";
			u4.MiddleInitial = "L";
			u4.Birthday = new DateTime(1997, 5, 16);
			u4.Street = "202 Bellmont Hall";
			u4.City =  "Round Rock";
			u4.State = State.TX;
			u4.Zip = "78681";
			u4.PhoneNumber  = "5125550133";
			u4.Email = "wchang@example.com";
			u4.UserName = "wchang@example.com";
			u4.PopcornPoints = 0;
			var result4 = UserManager.Create(u4, "texas1");
			db.SaveChanges();
			u4 = db.Users.FirstOrDefault(u => u.UserName == "wchang@example.com");
			UserManager.AddToRole(u4.Id, "Customer");
			db.SaveChanges();

			AppUser u5 = new AppUser();
			//u5.CustomerNumber = 5005;
			//u5.Password = "Anchorage";
			u5.LastName = "Chou";
			u5.FirstName = "Lim";
			u5.MiddleInitial = "";
			u5.Birthday = new DateTime(1970, 4, 6);
			u5.Street = "1600 Teresa Lane";
			u5.City =  "Austin";
			u5.State = State.TX;
			u5.Zip = "78705";
			u5.PhoneNumber  = "5125550102";
			u5.Email = "limchou@gogle.com";
			u5.UserName = "limchou@gogle.com";
			u5.PopcornPoints = 40;
			var result5 = UserManager.Create(u5, "Anchorage");
			db.SaveChanges();
			u5 = db.Users.FirstOrDefault(u => u.UserName == "limchou@gogle.com");
			UserManager.AddToRole(u5.Id, "Customer");
			db.SaveChanges();

			AppUser u6 = new AppUser();
			//u6.CustomerNumber = 5006;
			//u6.Password = "pepperoni";
			u6.LastName = "Dixon";
			u6.FirstName = "Shan";
			u6.MiddleInitial = "D";
			u6.Birthday = new DateTime(1984, 1, 12);
			u6.Street = "234 Holston Circle";
			u6.City =  "Austin";
			u6.State = State.TX;
			u6.Zip = "78712";
			u6.PhoneNumber  = "5125550146";
			u6.Email = "shdixon@aoll.com";
			u6.UserName = "shdixon@aoll.com";
			u6.PopcornPoints = 20;
			var result6 = UserManager.Create(u6, "pepperoni");
			db.SaveChanges();
			u6 = db.Users.FirstOrDefault(u => u.UserName == "shdixon@aoll.com");
			UserManager.AddToRole(u6.Id, "Customer");
			db.SaveChanges();

			AppUser u7 = new AppUser();
			//u7.CustomerNumber = 5007;
			//u7.Password = "longhorns";
			u7.LastName = "Evans";
			u7.FirstName = "Jim Bob";
			u7.MiddleInitial = "";
			u7.Birthday = new DateTime(1959, 9, 9);
			u7.Street = "506 Farrell Circle";
			u7.City =  "Georgetown";
			u7.State = State.TX;
			u7.Zip = "78628";
			u7.PhoneNumber  = "5125550170";
			u7.Email = "j.b.evans@aheca.org";
			u7.UserName = "j.b.evans@aheca.org";
			u7.PopcornPoints = 50;
			var result7 = UserManager.Create(u7, "longhorns");
			db.SaveChanges();
			u7 = db.Users.FirstOrDefault(u => u.UserName == "j.b.evans@aheca.org");
			UserManager.AddToRole(u7.Id, "Customer");
			db.SaveChanges();

			AppUser u8 = new AppUser();
			//u8.CustomerNumber = 5008;
			//u8.Password = "aggies";
			u8.LastName = "Feeley";
			u8.FirstName = "Lou Ann";
			u8.MiddleInitial = "K";
			u8.Birthday = new DateTime(2001, 1, 12);
			u8.Street = "600 S 8th Street W";
			u8.City =  "Austin";
			u8.State = State.TX;
			u8.Zip = "78746";
			u8.PhoneNumber  = "5125550105";
			u8.Email = "feeley@penguin.org";
			u8.UserName = "feeley@penguin.org";
			u8.PopcornPoints = 170;
			var result8 = UserManager.Create(u8, "aggies");
			db.SaveChanges();
			u8 = db.Users.FirstOrDefault(u => u.UserName == "feeley@penguin.org");
			UserManager.AddToRole(u8.Id, "Customer");
			db.SaveChanges();

			AppUser u9 = new AppUser();
			//u9.CustomerNumber = 5009;
			//u9.Password = "raiders";
			u9.LastName = "Freeley";
			u9.FirstName = "Tesa";
			u9.MiddleInitial = "P";
			u9.Birthday = new DateTime(1991, 2, 4);
			u9.Street = "4448 Fairview Ave.";
			u9.City =  "Horseshoe Bay";
			u9.State = State.TX;
			u9.Zip = "78657";
			u9.PhoneNumber  = "5125550114";
			u9.Email = "tfreeley@minnetonka.ci.us";
			u9.UserName = "tfreeley@minnetonka.ci.us";
			u9.PopcornPoints = 160;
			var result9 = UserManager.Create(u9, "raiders");
			db.SaveChanges();
			u9 = db.Users.FirstOrDefault(u => u.UserName == "tfreeley@minnetonka.ci.us");
			UserManager.AddToRole(u9.Id, "Customer");
			db.SaveChanges();

			AppUser u10 = new AppUser();
			//u10.CustomerNumber = 5010;
			//u10.Password = "mustangs";
			u10.LastName = "Garcia";
			u10.FirstName = "Margaret";
			u10.MiddleInitial = "L";
			u10.Birthday = new DateTime(1991, 10, 2);
			u10.Street = "594 Longview";
			u10.City =  "Austin";
			u10.State = State.TX;
			u10.Zip = "78727";
			u10.PhoneNumber  = "5125550155";
			u10.Email = "mgarcia@gogle.com";
			u10.UserName = "mgarcia@gogle.com";
			u10.PopcornPoints = 10;
			var result10 = UserManager.Create(u10, "mustangs");
			db.SaveChanges();
			u10 = db.Users.FirstOrDefault(u => u.UserName == "mgarcia@gogle.com");
			UserManager.AddToRole(u10.Id, "Customer");
			db.SaveChanges();

			AppUser u11 = new AppUser();
			//u11.CustomerNumber = 5011;
			//u11.Password = "onetime";
			u11.LastName = "Haley";
			u11.FirstName = "Charles";
			u11.MiddleInitial = "E";
			u11.Birthday = new DateTime(1974, 7, 10);
			u11.Street = "One Cowboy Pkwy";
			u11.City =  "Austin";
			u11.State = State.TX;
			u11.Zip = "78712";
			u11.PhoneNumber  = "5125550116";
			u11.Email = "chaley@thug.com";
			u11.UserName = "chaley@thug.com";
			u11.PopcornPoints = 40;
			var result11 = UserManager.Create(u11, "onetime");
			db.SaveChanges();
			u11 = db.Users.FirstOrDefault(u => u.UserName == "chaley@thug.com");
			UserManager.AddToRole(u11.Id, "Customer");
			db.SaveChanges();

			AppUser u12 = new AppUser();
			//u12.CustomerNumber = 5012;
			//u12.Password = "hampton1";
			u12.LastName = "Hampton";
			u12.FirstName = "Jeffrey";
			u12.MiddleInitial = "T.";
			u12.Birthday = new DateTime(2004, 3, 10);
			u12.Street = "337 38th St.";
			u12.City =  "San Marcos";
			u12.State = State.TX;
			u12.Zip = "78666";
			u12.PhoneNumber  = "5125550150";
			u12.Email = "jeffh@sonic.com";
			u11.UserName = "jeffh@sonic.com";
			u12.PopcornPoints = 150;
			var result12 = UserManager.Create(u12, "hampton1");
			db.SaveChanges();
			u12 = db.Users.FirstOrDefault(u => u.UserName == "jeffh@sonic.com");
			UserManager.AddToRole(u12.Id, "Customer");
			db.SaveChanges();

			AppUser u13 = new AppUser();
			//u13.CustomerNumber = 5013;
			//u13.Password = "jhearn22";
			u13.LastName = "Hearn";
			u13.FirstName = "John";
			u13.MiddleInitial = "B";
			u13.Birthday = new DateTime(1950, 8, 5);
			u13.Street = "4225 North First";
			u13.City =  "Austin";
			u13.State = State.TX;
			u13.Zip = "78705";
			u13.PhoneNumber  = "5125550196";
			u13.Email = "wjhearniii@umich.org";
			u13.UserName = "wjhearniii@umich.org";
			u13.PopcornPoints = 0;
			var result13 = UserManager.Create(u13, "jhearn22");
			db.SaveChanges();
			u13 = db.Users.FirstOrDefault(u => u.UserName == "wjhearniii@umich.org");
			UserManager.AddToRole(u13.Id, "Customer");
			db.SaveChanges();

			AppUser u14 = new AppUser();
			//u14.CustomerNumber = 5014;
			//u14.Password = "hickhickup";
			u14.LastName = "Hicks";
			u14.FirstName = "Anthony";
			u14.MiddleInitial = "J";
			u14.Birthday = new DateTime(2004, 12, 8);
			u14.Street = "32 NE Garden Ln., Ste 910";
			u14.City =  "Austin";
			u14.State = State.TX;
			u14.Zip = "78712";
			u14.PhoneNumber  = "5125550188";
			u14.Email = "ahick@yaho.com";
			u14.UserName = "ahick@yaho.com";
			u14.PopcornPoints = 60;
			var result14 = UserManager.Create(u14, "hickhickup");
			db.SaveChanges();
			u14 = db.Users.FirstOrDefault(u => u.UserName == "ahick@yaho.com");
			UserManager.AddToRole(u14.Id, "Customer");
			db.SaveChanges();

			AppUser u15 = new AppUser();
			//u15.CustomerNumber = 5015;
			//u15.Password = "ingram2015";
			u15.LastName = "Ingram";
			u15.FirstName = "Brad";
			u15.MiddleInitial = "S.";
			u15.Birthday = new DateTime(2001, 9, 5);
			u15.Street = "6548 La Posada Ct.";
			u15.City =  "New York";
			u15.State = State.NY;
			u15.Zip = "10101";
			u15.PhoneNumber  = "5125550116";
			u15.Email = "ingram@jack.com";
			u15.UserName = "ingram@jack.com";
			u15.PopcornPoints = 20;
			var result15 = UserManager.Create(u15, "ingram2015");
			db.SaveChanges();
			u15 = db.Users.FirstOrDefault(u => u.UserName == "ingram@jack.com");
			UserManager.AddToRole(u15.Id, "Customer");
			db.SaveChanges();

			AppUser u16 = new AppUser();
			//u16.CustomerNumber = 5016;
			//u16.Password = "toddy25";
			u16.LastName = "Jacobs";
			u16.FirstName = "Todd";
			u16.MiddleInitial = "L.";
			u16.Birthday = new DateTime(1999, 1, 20);
			u16.Street = "4564 Elm St.";
			u16.City =  "Austin";
			u16.State = State.TX;
			u16.Zip = "78729";
			u16.PhoneNumber  = "5125550166";
			u16.Email = "toddj@yourmom.com";
			u16.UserName = "toddj@yourmom.com";
			u16.PopcornPoints = 170;
			var result16 = UserManager.Create(u16, "toddy25");
			db.SaveChanges();
			u16 = db.Users.FirstOrDefault(u => u.UserName == "toddj@yourmom.com");
			UserManager.AddToRole(u16.Id, "Customer");
			db.SaveChanges();

			AppUser u17 = new AppUser();
			//u17.CustomerNumber = 5017;
			//u17.Password = "something";
			u17.LastName = "Lawrence";
			u17.FirstName = "Victoria";
			u17.MiddleInitial = "M.";
			u17.Birthday = new DateTime(2000, 4, 14);
			u17.Street = "6639 Butterfly Ln.";
			u17.City =  "Beverly Hills";
			u17.State = State.CA;
			u17.Zip = "90210";
			u17.PhoneNumber  = "5125550173";
			u17.Email = "thequeen@aska.net";
			u17.UserName = "thequeen@aska.net";
			u17.PopcornPoints = 130;
			var result17 = UserManager.Create(u17, "something");
			db.SaveChanges();
			u17 = db.Users.FirstOrDefault(u => u.UserName == "thequeen@aska.net");
			UserManager.AddToRole(u17.Id, "Customer");
			db.SaveChanges();

			AppUser u18 = new AppUser();
			//u18.CustomerNumber = 5018;
			//u18.Password = "Password1";
			u18.LastName = "Lineback";
			u18.FirstName = "Erik";
			u18.MiddleInitial = "W";
			u18.Birthday = new DateTime(2003, 12, 2);
			u18.Street = "1300 Netherland St";
			u18.City =  "Austin";
			u18.State = State.TX;
			u18.Zip = "78758";
			u18.PhoneNumber  = "5125550167";
			u18.Email = "linebacker@gogle.com";
			u18.UserName = "linebacker@gogle.com";
			u18.PopcornPoints = 60;
			var result18 = UserManager.Create(u18, "Password1");
			db.SaveChanges();
			u18 = db.Users.FirstOrDefault(u => u.UserName == "linebacker@gogle.com");
			UserManager.AddToRole(u18.Id, "Customer");
			db.SaveChanges();

			AppUser u19 = new AppUser();
			//u19.CustomerNumber = 5019;
			//u19.Password = "aclfest2017";
			u19.LastName = "Lowe";
			u19.FirstName = "Ernest";
			u19.MiddleInitial = "S";
			u19.Birthday = new DateTime(1977, 12, 7);
			u19.Street = "3201 Pine Drive";
			u19.City =  "New Braunfels";
			u19.State = State.TX;
			u19.Zip = "78130";
			u19.PhoneNumber  = "5125550187";
			u19.Email = "elowe@netscare.net";
			u19.UserName = "elowe@netscare.net";
			u19.PopcornPoints = 20;
			var result19 = UserManager.Create(u19, "aclfest2017");
			db.SaveChanges();
			u19 = db.Users.FirstOrDefault(u => u.UserName == "elowe@netscare.net");
			UserManager.AddToRole(u19.Id, "Customer");
			db.SaveChanges();

			AppUser u20 = new AppUser();
			//u20.CustomerNumber = 5020;
			//u20.Password = "nothinggood";
			u20.LastName = "Luce";
			u20.FirstName = "Chuck";
			u20.MiddleInitial = "B";
			u20.Birthday = new DateTime(1949, 3, 16);
			u20.Street = "2345 Rolling Clouds";
			u20.City =  "Cactus";
			u20.State = State.TX;
			u20.Zip = "79013";
			u20.PhoneNumber  = "5125550141";
			u20.Email = "cluce@gogle.com";
			u20.UserName = "cluce@gogle.com";
			u20.PopcornPoints = 180;
			var result20 = UserManager.Create(u20, "nothinggood");
			db.SaveChanges();
			u20 = db.Users.FirstOrDefault(u => u.UserName == "cluce@gogle.com");
			UserManager.AddToRole(u20.Id, "Customer");
			db.SaveChanges();

			AppUser u21 = new AppUser();
			//u21.CustomerNumber = 5021;
			//u21.Password = "whatever";
			u21.LastName = "MacLeod";
			u21.FirstName = "Jennifer";
			u21.MiddleInitial = "D.";
			u21.Birthday = new DateTime(1947, 2, 21);
			u21.Street = "2504 Far West Blvd.";
			u21.City =  "Marble Falls";
			u21.State = State.TX;
			u21.Zip = "78654";
			u21.PhoneNumber  = "5125550185";
			u21.Email = "mackcloud@george.com";
			u21.UserName = "mackcloud@george.com";
			u21.PopcornPoints = 170;
			var result21 = UserManager.Create(u21, "whatever");
			db.SaveChanges();
			u21 = db.Users.FirstOrDefault(u => u.UserName == "mackcloud@george.com");
			UserManager.AddToRole(u21.Id, "Customer");
			db.SaveChanges();

			AppUser u22 = new AppUser();
			//u22.CustomerNumber = 5022;
			//u22.Password = "whocares";
			u22.LastName = "Markham";
			u22.FirstName = "Elizabeth";
			u22.MiddleInitial = "P.";
			u22.Birthday = new DateTime(1972, 3, 20);
			u22.Street = "7861 Chevy Chase";
			u22.City =  "Kissimmee";
			u22.State = State.FL;
			u22.Zip = "34741";
			u22.PhoneNumber  = "5125550134";
			u22.Email = "cmartin@beets.com";
			u22.UserName = "cmartin@beets.com";
			u22.PopcornPoints = 100;
			var result22 = UserManager.Create(u22, "whocares");
			db.SaveChanges();
			u22 = db.Users.FirstOrDefault(u => u.UserName == "cmartin@beets.com");
			UserManager.AddToRole(u22.Id, "Customer");
			db.SaveChanges();

			AppUser u23 = new AppUser();
			//u23.CustomerNumber = 5023;
			//u23.Password = "xcellent";
			u23.LastName = "Martin";
			u23.FirstName = "Clarence";
			u23.MiddleInitial = "A";
			u23.Birthday = new DateTime(1992, 7, 19);
			u23.Street = "87 Alcedo St.";
			u23.City =  "Austin";
			u23.State = State.TX;
			u23.Zip = "78709";
			u23.PhoneNumber  = "5125550151";
			u23.Email = "clarence@yoho.com";
			u23.UserName = "clarence@yoho.com";
			u23.PopcornPoints = 130;
			var result23 = UserManager.Create(u23, "xcellent");
			db.SaveChanges();
			u23 = db.Users.FirstOrDefault(u => u.UserName == "clarence@yoho.com");
			UserManager.AddToRole(u23.Id, "Customer");
			db.SaveChanges();

			AppUser u24 = new AppUser();
			//u24.CustomerNumber = 5024;
			//u24.Password = "snowsnow";
			u24.LastName = "Martinez";
			u24.FirstName = "Gregory";
			u24.MiddleInitial = "R.";
			u24.Birthday = new DateTime(1947, 5, 28);
			u24.Street = "8295 Sunset Blvd.";
			u24.City =  "Red Rock";
			u24.State = State.TX;
			u24.Zip = "78662";
			u24.PhoneNumber  = "5125550120";
			u24.Email = "gregmartinez@drdre.com";
			u24.UserName = "gregmartinez@drdre.com";
			u24.PopcornPoints = 20;
			var result24 = UserManager.Create(u24, "snowsnow");
			db.SaveChanges();
			u24 = db.Users.FirstOrDefault(u => u.UserName == "gregmartinez@drdre.com");
			UserManager.AddToRole(u24.Id, "Customer");
			db.SaveChanges();

			AppUser u25 = new AppUser();
			//u25.CustomerNumber = 5025;
			//u25.Password = "mydogspot";
			u25.LastName = "Miller";
			u25.FirstName = "Charles";
			u25.MiddleInitial = "R.";
			u25.Birthday = new DateTime(1990, 10, 15);
			u25.Street = "8962 Main St.";
			u25.City =  "South Padre Island";
			u25.State = State.TX;
			u25.Zip = "78597";
			u25.PhoneNumber  = "5125550198";
			u25.Email = "cmiller@bob.com";
			u25.UserName = "cmiller@bob.com";
			u25.PopcornPoints = 20;
			var result25 = UserManager.Create(u25, "mydogspot");
			db.SaveChanges();
			u25 = db.Users.FirstOrDefault(u => u.UserName == "banker@longhorn.net");
			UserManager.AddToRole(u25.Id, "Customer");
			db.SaveChanges();

			AppUser u26 = new AppUser();
			//u26.CustomerNumber = 5026;
			//u26.Password = "spotmydog";
			u26.LastName = "Nelson";
			u26.FirstName = "Kelly";
			u26.MiddleInitial = "T";
			u26.Birthday = new DateTime(1971, 7, 13);
			u26.Street = "2601 Red River";
			u26.City =  "Disney";
			u26.State = State.OK;
			u26.Zip = "74340";
			u26.PhoneNumber  = "5125550177";
			u26.Email = "knelson@aoll.com";
			u26.UserName = "knelson@aoll.com";
			u26.PopcornPoints = 110;
			var result26 = UserManager.Create(u26, "spotmydog");
			db.SaveChanges();
			u26 = db.Users.FirstOrDefault(u => u.UserName == "knelson@aoll.com");
			UserManager.AddToRole(u26.Id, "Customer");
			db.SaveChanges();

			AppUser u27 = new AppUser();
			//u27.CustomerNumber = 5027;
			//u27.Password = "joejoejoe";
			u27.LastName = "Nguyen";
			u27.FirstName = "Joe";
			u27.MiddleInitial = "C";
			u27.Birthday = new DateTime(1984, 3, 17);
			u27.Street = "1249 4th SW St.";
			u27.City =  "Del Rio";
			u27.State = State.TX;
			u27.Zip = "78841";
			u27.PhoneNumber  = "5125550174";
			u27.Email = "joewin@xfactor.com";
			u27.UserName = "joewin@xfactor.com";
			u27.PopcornPoints = 150;
			var result27 = UserManager.Create(u27, "joejoejoe");
			db.SaveChanges();
			u27 = db.Users.FirstOrDefault(u => u.UserName == "joewin@xfactor.com");
			UserManager.AddToRole(u27.Id, "Customer");
			db.SaveChanges();

			AppUser u28 = new AppUser();
			//u28.CustomerNumber = 5028;
			//u28.Password = "billyboy";
			u28.LastName = "O'Reilly";
			u28.FirstName = "Bill";
			u28.MiddleInitial = "T";
			u28.Birthday = new DateTime(1959, 7, 8);
			u28.Street = "8800 Gringo Drive";
			u28.City =  "Austin";
			u28.State = State.TX;
			u28.Zip = "78746";
			u28.PhoneNumber  = "5125550167";
			u28.Email = "orielly@foxnews.cnn";
			u28.UserName = "orielly@foxnews.cnn";
			u28.PopcornPoints = 190;
			var result28 = UserManager.Create(u28, "billyboy");
			db.SaveChanges();
			u28 = db.Users.FirstOrDefault(u => u.UserName == "orielly@foxnews.cnn");
			UserManager.AddToRole(u28.Id, "Customer");
			db.SaveChanges();

			AppUser u29 = new AppUser();
			//u29.CustomerNumber = 5029;
			//u29.Password = "radgirl";
			u29.LastName = "Radkovich";
			u29.FirstName = "Anka";
			u29.MiddleInitial = "L";
			u29.Birthday = new DateTime(1966, 5, 19);
			u29.Street = "1300 Elliott Pl";
			u29.City =  "Austin";
			u29.State = State.TX;
			u29.Zip = "78712";
			u29.PhoneNumber  = "5125550151";
			u29.Email = "ankaisrad@gogle.com";
			u29.UserName = "ankaisrad@gogle.com";
			u29.PopcornPoints = 120;
			var result29 = UserManager.Create(u29, "radgirl");
			db.SaveChanges();
			u29 = db.Users.FirstOrDefault(u => u.UserName == "ankaisrad@gogle.com");
			UserManager.AddToRole(u29.Id, "Customer");
			db.SaveChanges();

			AppUser u30 = new AppUser();
			//u30.CustomerNumber = 5030;
			//u30.Password = "meganr34";
			u30.LastName = "Rhodes";
			u30.FirstName = "Megan";
			u30.MiddleInitial = "C.";
			u30.Birthday = new DateTime(1965, 3, 12);
			u30.Street = "4587 Enfield Rd.";
			u30.City =  "Austin";
			u30.State = State.TX;
			u30.Zip = "78705";
			u30.PhoneNumber  = "5125550133";
			u30.Email = "megrhodes@freserve.co.uk";
			u30.UserName = "megrhodes@freserve.co.uk";
			u30.PopcornPoints = 190;
			var result30 = UserManager.Create(u30, "meganr34");
			db.SaveChanges();
			u30 = db.Users.FirstOrDefault(u => u.UserName == "megrhodes@freserve.co.uk");
			UserManager.AddToRole(u30.Id, "Customer");
			db.SaveChanges();

			AppUser u31 = new AppUser();
			//u31.CustomerNumber = 5031;
			//u31.Password = "ricearoni";
			u31.LastName = "Rice";
			u31.FirstName = "Eryn";
			u31.MiddleInitial = "M.";
			u31.Birthday = new DateTime(1975, 4, 28);
			u31.Street = "3405 Rio Grande";
			u31.City =  "Austin";
			u31.State = State.TX;
			u31.Zip = "78785";
			u31.PhoneNumber  = "5125550196";
			u31.Email = "erynrice@aoll.com";
			u31.UserName = "erynrice@aoll.com";
			u31.PopcornPoints = 190;
			var result31 = UserManager.Create(u31, "ricearoni");
			db.SaveChanges();
			u31 = db.Users.FirstOrDefault(u => u.UserName == "erynrice@aoll.com");
			UserManager.AddToRole(u31.Id, "Customer");
			db.SaveChanges();

			AppUser u32 = new AppUser();
			//u32.CustomerNumber = 5032;
			//u32.Password = "jrod2017";
			u32.LastName = "Rodriguez";
			u32.FirstName = "Jorge";
			u32.MiddleInitial = "";
			u32.Birthday = new DateTime(1953, 12, 8);
			u32.Street = "6788 Cotter Street";
			u32.City =  "Littlefield";
			u32.State = State.TX;
			u32.Zip = "79339";
			u32.PhoneNumber  = "5125550141";
			u32.Email = "jorge@noclue.com";
			u32.UserName = "jorge@noclue.com";
			u32.PopcornPoints = 20;
			var result32 = UserManager.Create(u32, "jrod2017");
			db.SaveChanges();
			u32 = db.Users.FirstOrDefault(u => u.UserName == "jorge@noclue.com");
			UserManager.AddToRole(u32.Id, "Customer");
			db.SaveChanges();

			AppUser u33 = new AppUser();
			//u33.CustomerNumber = 5033;
			//u33.Password = "rogerthat";
			u33.LastName = "Rogers";
			u33.FirstName = "Allen";
			u33.MiddleInitial = "B.";
			u33.Birthday = new DateTime(1973, 4, 22);
			u33.Street = "4965 Oak Hill";
			u33.City =  "Austin";
			u33.State = State.TX;
			u33.Zip = "78733";
			u33.PhoneNumber  = "5125550189";
			u33.Email = "mrrogers@lovelyday.com";
			u33.UserName = "mrrogers@lovelyday.com";
			u33.PopcornPoints = 100;
			var result33 = UserManager.Create(u33, "rogerthat");
			db.SaveChanges();
			u33 = db.Users.FirstOrDefault(u => u.UserName == "mrrogers@lovelyday.com");
			UserManager.AddToRole(u33.Id, "Customer");
			db.SaveChanges();

			AppUser u34 = new AppUser();
			//u34.CustomerNumber = 5034;
			//u34.Password = "bunnyhop";
			u34.LastName = "Saint-Jean";
			u34.FirstName = "Olivier";
			u34.MiddleInitial = "M";
			u34.Birthday = new DateTime(1995, 2, 19);
			u34.Street = "255 Toncray Dr.";
			u34.City =  "Austin";
			u34.State = State.TX;
			u34.Zip = "78755";
			u34.PhoneNumber  = "5125550152";
			u34.Email = "stjean@athome.com";
			u34.UserName = "stjean@athome.com";
			u34.PopcornPoints = 250;
			var result34 = UserManager.Create(u34, "bunnyhop");
			db.SaveChanges();
			u34 = db.Users.FirstOrDefault(u => u.UserName == "stjean@athome.com");
			UserManager.AddToRole(u34.Id, "Customer");
			db.SaveChanges();

			AppUser u35 = new AppUser();
			//u35.CustomerNumber = 5035;
			//u35.Password = "penguin12";
			u35.LastName = "Saunders";
			u35.FirstName = "Sarah";
			u35.MiddleInitial = "J.";
			u35.Birthday = new DateTime(1978, 2, 19);
			u35.Street = "332 Avenue C";
			u35.City =  "Austin";
			u35.State = State.TX;
			u35.Zip = "78701";
			u35.PhoneNumber  = "5125550146";
			u35.Email = "saunders@pen.com";
			u35.UserName = "saunders@pen.com";
			u35.PopcornPoints = 40;
			var result35 = UserManager.Create(u35, "penguin12");
			db.SaveChanges();
			u35 = db.Users.FirstOrDefault(u => u.UserName == "saunders@pen.com");
			UserManager.AddToRole(u35.Id, "Customer");
			db.SaveChanges();

			AppUser u36 = new AppUser();
			//u36.CustomerNumber = 5036;
			//u36.Password = "alaskaboy";
			u36.LastName = "Sewell";
			u36.FirstName = "William";
			u36.MiddleInitial = "T.";
			u36.Birthday = new DateTime(2004, 12, 23);
			u36.Street = "2365 51st St.";
			u36.City =  "El Paso";
			u36.State = State.TX;
			u36.Zip = "79953";
			u36.PhoneNumber  = "5125550192";
			u36.Email = "willsheff@email.com";
			u36.UserName = "willsheff@email.com";
			u36.PopcornPoints = 200;
			var result36 = UserManager.Create(u36, "alaskaboy");
			db.SaveChanges();
			u36 = db.Users.FirstOrDefault(u => u.UserName == "willsheff@email.com");
			UserManager.AddToRole(u36.Id, "Customer");
			db.SaveChanges();

			AppUser u37 = new AppUser();
			//u37.CustomerNumber = 5037;
			//u37.Password = "martin1234";
			u37.LastName = "Sheffield";
			u37.FirstName = "Martin";
			u37.MiddleInitial = "J.";
			u37.Birthday = new DateTime(1960, 5, 8);
			u37.Street = "3886 Avenue A";
			u37.City =  "Balmorhea";
			u37.State = State.TX;
			u37.Zip = "79718";
			u37.PhoneNumber  = "5125550131";
			u37.Email = "sheffiled@gogle.com";
			u37.UserName = "sheffiled@gogle.com";
			u37.PopcornPoints = 130;
			var result37 = UserManager.Create(u37, "martin1234");
			db.SaveChanges();
			u37 = db.Users.FirstOrDefault(u => u.UserName == "sheffiled@gogle.com");
			UserManager.AddToRole(u37.Id, "Customer");
			db.SaveChanges();

			AppUser u38 = new AppUser();
			//u38.CustomerNumber = 5038;
			//u38.Password = "smitty444";
			u38.LastName = "Smith";
			u38.FirstName = "John";
			u38.MiddleInitial = "A";
			u38.Birthday = new DateTime(1955, 6, 25);
			u38.Street = "23 Hidden Forge Dr.";
			u38.City =  "Austin";
			u38.State = State.TX;
			u38.Zip = "78760";
			u38.PhoneNumber  = "5125550190";
			u38.Email = "johnsmith187@aoll.com";
			u38.UserName = "johnsmith187@aoll.com";
			u38.PopcornPoints = 130;
			var result38 = UserManager.Create(u38, "smitty444");
			db.SaveChanges();
			u38 = db.Users.FirstOrDefault(u => u.UserName == "johnsmith187@aoll.com");
			UserManager.AddToRole(u38.Id, "Customer"); ;
			db.SaveChanges();

			AppUser u39 = new AppUser();
			//u39.CustomerNumber = 5039;
			//u39.Password = "dustydusty";
			u39.LastName = "Stroud";
			u39.FirstName = "Dustin";
			u39.MiddleInitial = "P";
			u39.Birthday = new DateTime(1967, 7, 26);
			u39.Street = "1212 Rita Rd";
			u39.City =  "Austin";
			u39.State = State.TX;
			u39.Zip = "78734";
			u39.PhoneNumber  = "5125550157";
			u39.Email = "dustroud@mail.com";
			u39.UserName = "dustroud@mail.com";
			u39.PopcornPoints = 90;
			var result39 = UserManager.Create(u39, "dustydusty");
			db.SaveChanges();
			u39 = db.Users.FirstOrDefault(u => u.UserName == "dustroud@mail.com");
			UserManager.AddToRole(u39.Id, "Customer");
			db.SaveChanges();

			AppUser u40 = new AppUser();
			//u40.CustomerNumber = 5040;
			//u40.Password = "stewball";
			u40.LastName = "Stuart";
			u40.FirstName = "Eric";
			u40.MiddleInitial = "D.";
			u40.Birthday = new DateTime(1947, 12, 4);
			u40.Street = "5576 Toro Ring";
			u40.City =  "Kyle";
			u40.State = State.TX;
			u40.Zip = "78640";
			u40.PhoneNumber  = "5125550191";
			u40.Email = "estuart@anchor.net";
			u40.UserName = "estuart@anchor.net";
			u40.PopcornPoints = 170;
			var result40 = UserManager.Create(u40, "stewball");
			db.SaveChanges();
			u40 = db.Users.FirstOrDefault(u => u.UserName == "estuart@anchor.net");
			UserManager.AddToRole(u40.Id, "Customer");
			db.SaveChanges();

			AppUser u41 = new AppUser();
			//u41.CustomerNumber = 5041;
			//u41.Password = "slowwind";
			u41.LastName = "Stump";
			u41.FirstName = "Peter";
			u41.MiddleInitial = "L";
			u41.Birthday = new DateTime(1974, 7, 10);
			u41.Street = "1300 Kellen Circle";
			u41.City =  "Philadelphia";
			u41.State = State.PA;
			u41.Zip = "19123";
			u41.PhoneNumber  = "5125550136";
			u41.Email = "peterstump@noclue.com";
			u41.UserName = "peterstump@noclue.com";
			u41.PopcornPoints = 50;
			var result41 = UserManager.Create(u41, "slowwind");
			db.SaveChanges();
			u41 = db.Users.FirstOrDefault(u => u.UserName == "peterstump@noclue.com");
			UserManager.AddToRole(u41.Id, "Customer");
			db.SaveChanges();

			AppUser u42 = new AppUser();
			//u42.CustomerNumber = 5042;
			//u42.Password = "tanner5454";
			u42.LastName = "Tanner";
			u42.FirstName = "Jeremy";
			u42.MiddleInitial = "S.";
			u42.Birthday = new DateTime(1944, 1, 11);
			u42.Street = "4347 Almstead";
			u42.City =  "Austin";
			u42.State = State.TX;
			u42.Zip = "78747";
			u42.PhoneNumber  = "5125550170";
			u42.Email = "jtanner@mustang.net";
			u42.UserName = "jtanner@mustang.net";
			u42.PopcornPoints = 190;
			var result42 = UserManager.Create(u42, "tanner5454");
			db.SaveChanges();
			u42 = db.Users.FirstOrDefault(u => u.UserName == "jtanner@mustang.net");
			UserManager.AddToRole(u42.Id, "Customer");
			db.SaveChanges();

			AppUser u43 = new AppUser();
			//u43.CustomerNumber = 5043;
			//u43.Password = "allyrally";
			u43.LastName = "Taylor";
			u43.FirstName = "Allison";
			u43.MiddleInitial = "R.";
			u43.Birthday = new DateTime(1990, 11, 14);
			u43.Street = "467 Nueces St.";
			u43.City =  "Austin";
			u43.State = State.TX;
			u43.Zip = "78712";
			u43.PhoneNumber  = "5125550160";
			u43.Email = "taylordjay@aoll.com";
			u43.UserName = "taylordjay@aoll.com";
			u43.PopcornPoints = 110;
			var result43 = UserManager.Create(u43, "allyrally");
			db.SaveChanges();
			u43 = db.Users.FirstOrDefault(u => u.UserName == "taylordjay@aoll.com");
			UserManager.AddToRole(u43.Id, "Customer");
			db.SaveChanges();

			AppUser u44 = new AppUser();
			//u44.CustomerNumber = 5044;
			//u44.Password = "taylorbaylor";
			u44.LastName = "Taylor";
			u44.FirstName = "Rachel";
			u44.MiddleInitial = "K.";
			u44.Birthday = new DateTime(1976, 1, 18);
			u44.Street = "345 Longview Dr.";
			u44.City =  "Austin";
			u44.State = State.TX;
			u44.Zip = "78758";
			u44.PhoneNumber  = "5125550127";
			u44.Email = "rtaylor@gogle.com";
			u44.UserName = "rtaylor@gogle.com";
			u44.PopcornPoints = 160;
			var result44 = UserManager.Create(u44, "taylorbaylor");
			db.SaveChanges();
			u44 = db.Users.FirstOrDefault(u => u.UserName == "rtaylor@gogle.com");
			UserManager.AddToRole(u44.Id, "Customer");
			db.SaveChanges();

			AppUser u45 = new AppUser();
			//u45.CustomerNumber = 5045;
			//u45.Password = "teeoff22";
			u45.LastName = "Tee";
			u45.FirstName = "Frank";
			u45.MiddleInitial = "J";
			u45.Birthday = new DateTime(1998, 9, 6);
			u45.Street = "5590 Lavell Dr";
			u45.City =  "Austin";
			u45.State = State.TX;
			u45.Zip = "78729";
			u45.PhoneNumber  = "5125550161";
			u45.Email = "teefrank@noclue.com";
			u45.UserName = "teefrank@noclue.com";
			u45.PopcornPoints = 70;
			var result45 = UserManager.Create(u45, "teeoff22");
			db.SaveChanges();
			u45 = db.Users.FirstOrDefault(u => u.UserName == "teefrank@noclue.com");
			UserManager.AddToRole(u45.Id, "Customer");
			db.SaveChanges();

			AppUser u46 = new AppUser();
			//u46.CustomerNumber = 5046;
			//u46.Password = "tucksack1";
			u46.LastName = "Tucker";
			u46.FirstName = "Clent";
			u46.MiddleInitial = "J";
			u46.Birthday = new DateTime(1943, 2, 25);
			u46.Street = "312 Main St.";
			u46.City =  "Round Rock";
			u46.State = State.TX;
			u46.Zip = "78665";
			u46.PhoneNumber  = "5125550106";
			u46.Email = "ctucker@alphabet.co.uk";
			u46.UserName = "ctucker@alphabet.co.uk";
			u46.PopcornPoints = 150;
			var result46 = UserManager.Create(u46, "tucksack1");
			db.SaveChanges();
			u46 = db.Users.FirstOrDefault(u => u.UserName == "ctucker@alphabet.co.uk");
			UserManager.AddToRole(u46.Id, "Customer");
			db.SaveChanges();

			AppUser u47 = new AppUser();
			//u47.CustomerNumber = 5047;
			//u47.Password = "meow88";
			u47.LastName = "Velasco";
			u47.FirstName = "Allen";
			u47.MiddleInitial = "G";
			u47.Birthday = new DateTime(1985, 9, 10);
			u47.Street = "679 W. 4th";
			u47.City =  "Cedar Park";
			u47.State = State.TX;
			u47.Zip = "78613";
			u47.PhoneNumber  = "5125550170";
			u47.Email = "avelasco@yoho.com";
			u47.UserName = "avelasco@yoho.com";
			u47.PopcornPoints = 0;
			var result47 = UserManager.Create(u47, "meow88");
			db.SaveChanges();
			u47 = db.Users.FirstOrDefault(u => u.UserName == "avelasco@yoho.com");
			UserManager.AddToRole(u47.Id, "Customer");
			db.SaveChanges();

			AppUser u48 = new AppUser();
			//u48.CustomerNumber = 5048;
			//u48.Password = "vinovino";
			u48.LastName = "Vino";
			u48.FirstName = "Janet";
			u48.MiddleInitial = "E";
			u48.Birthday = new DateTime(1985, 2, 7);
			u48.Street = "189 Grape Road";
			u48.City =  "Lockhart";
			u48.State = State.TX;
			u48.Zip = "78644";
			u48.PhoneNumber  = "5125550128";
			u48.Email = "vinovino@grapes.com";
			u48.UserName = "vinovino@grapes.com";
			u48.PopcornPoints = 160;
			var result48 = UserManager.Create(u48, "vinovino");
			db.SaveChanges();
			u48 = db.Users.FirstOrDefault(u => u.UserName == "vinovino@grapes.com");
			UserManager.AddToRole(u48.Id, "Customer");
			db.SaveChanges();

			AppUser u49 = new AppUser();
			//u49.CustomerNumber = 5049;
			//u49.Password = "gowest";
			u49.LastName = "West";
			u49.FirstName = "Jake";
			u49.MiddleInitial = "T";
			u49.Birthday = new DateTime(1976, 1, 9);
			u49.Street = "RR 3287";
			u49.City =  "Austin";
			u49.State = State.TX;
			u49.Zip = "78705";
			u49.PhoneNumber  = "2025550170";
			u49.Email = "westj@pioneer.net";
			u49.UserName = "westj@pioneer.net";
			u49.PopcornPoints = 70;
			var result49 = UserManager.Create(u49, "gowest");
			db.SaveChanges();
			u49 = db.Users.FirstOrDefault(u => u.UserName == "westj@pioneer.net");
			UserManager.AddToRole(u49.Id, "Customer");
			db.SaveChanges();

			AppUser u50 = new AppUser();
			//u50.CustomerNumber = 5050;
			//u50.Password = "louielouie";
			u50.LastName = "Winthorpe";
			u50.FirstName = "Louis";
			u50.MiddleInitial = "L";
			u50.Birthday = new DateTime(1953, 4, 19);
			u50.Street = "2500 Padre Blvd";
			u50.City =  "Austin";
			u50.State = State.TX;
			u50.Zip = "78747";
			u50.PhoneNumber  = "2025550141";
			u50.Email = "winner@hootmail.com";
			u50.UserName = "winner@hootmail.com";
			u50.PopcornPoints = 150;
			var result50 = UserManager.Create(u50, "louielouie");
			db.SaveChanges();
			u50 = db.Users.FirstOrDefault(u => u.UserName == "winner@hootmail.com");
			UserManager.AddToRole(u50.Id, "Customer");
			db.SaveChanges();

			AppUser u51 = new AppUser();
			//u51.CustomerNumber = 5051;
			//u51.Password = "woodyman1";
			u51.LastName = "Wood";
			u51.FirstName = "Reagan";
			u51.MiddleInitial = "B.";
			u51.Birthday = new DateTime(2002, 12, 28);
			u51.Street = "447 Westlake Dr.";
			u51.City =  "Austin";
			u51.State = State.TX;
			u51.Zip = "78753";
			u51.PhoneNumber  = "2025550128";
			u51.Email = "rwood@voyager.net";
			u51.UserName = "rwood@voyager.net";
			u51.PopcornPoints = 20;
			var result51 = UserManager.Create(u51, "woodyman1");
			db.SaveChanges();
			u51 = db.Users.FirstOrDefault(u => u.UserName == "rwood@voyager.net");
			UserManager.AddToRole(u51.Id, "Customer");
			db.SaveChanges();

		}
	}
}
