using AWO_Team14.Models;
using AWO_Team14.DAL;
using System.Data.Entity.Migrations;
using System;
using System.Linq;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;

namespace AWO_Team14.Migrations
{
	public class EmployeeData
	{
		public void SeedEmployees(AppDbContext db)
		{
			//create a user manager and a role manager to use for this method
			AppUserManager UserManager = new AppUserManager(new UserStore<AppUser>(db));


			//UserManager.PasswordValidator = new PasswordValidator
			//{
			//	RequiredLength = 6,
			//	RequireNonLetterOrDigit = false,
			//	RequireDigit = true,
			//	RequireLowercase = true,
			//	RequireUppercase = true
			//};

			UserManager.PasswordValidator = new PasswordValidator
			{
				RequiredLength = 6,
				RequireNonLetterOrDigit = false,
				RequireDigit = false,
				RequireLowercase = false,
				RequireUppercase = false
			};

			AppUser u1 = new AppUser();
			//u1.Password = "society";
			u1.LastName = "Jacobs";
			u1.FirstName = "Todd";
			u1.MiddleInitial = "L";
			u1.Birthday = new DateTime(1958, 4, 25);
			u1.Street = "4564 Elm St.";
			u1.City = "Georgetown";
			//u1.EmpType = enumUserType."Employee";
			u1.State = State.TX;
			u1.Zip = "78628";
			u1.PhoneNumber = "9074653365";
			u1.Email = "t.jacobs@longhorncinema.com";
			u1.UserName = "t.jacobs@longhorncinema.com";
			u1.Archived = false;
			var result1 = UserManager.Create(u1, "society");
			db.SaveChanges();
			u1 = db.Users.FirstOrDefault(u => u.UserName == "t.jacobs@longhorncinema.com");
			UserManager.AddToRole(u1.Id, "Employee");
			db.SaveChanges();

			AppUser u2 = new AppUser();
			//u2.Password = "ricearoni";
			u2.LastName = "Rice";
			u2.FirstName = "Eryn";
			u2.MiddleInitial = "M";
			u2.Birthday = new DateTime(1959, 7, 2);
			u2.Street = "3405 Rio Grande";
			u2.City = "Austin";
			//u2.EmpType = enumUserType."Manager";
			u2.State = State.TX;
			u2.Zip = "78746";
			u2.PhoneNumber = "9073876657";
			u2.Email = "e.rice@longhorncinema.com";
			u2.UserName = "e.rice@longhorncinema.com";
			u2.Archived = false;
			var result2 = UserManager.Create(u2, "ricearoni");
			db.SaveChanges();
			u2 = db.Users.FirstOrDefault(u => u.UserName == "e.rice@longhorncinema.com");
			UserManager.AddToRole(u2.Id, "Manager");
			db.SaveChanges();

			AppUser u3 = new AppUser();
			//u3.Password = "ingram45";
			u3.LastName = "Ingram";
			u3.FirstName = "Brad";
			u3.MiddleInitial = "S";
			u3.Birthday = new DateTime(1962, 8, 25);
			u3.Street = "6548 La Posada Ct.";
			u3.City = "Austin";
			//u3.EmpType = enumUserType."Employee";
			u3.State = State.TX;
			u3.Zip = "78705";
			u3.PhoneNumber = "9074678821";
			u3.Email = "b.ingram@longhorncinema.com";
			u3.UserName = "b.ingram@longhorncinema.com";
			u3.Archived = false;
			var result3 = UserManager.Create(u3, "ingram45");
			db.SaveChanges();
			u3 = db.Users.FirstOrDefault(u => u.UserName == "b.ingram@longhorncinema.com");
			UserManager.AddToRole(u3.Id, "Employee");
			db.SaveChanges();

			AppUser u4 = new AppUser();
			//u4.Password = "nostalgic";
			u4.LastName = "Taylor";
			u4.FirstName = "Allison";
			u4.MiddleInitial = "R";
			u4.Birthday = new DateTime(1964, 9, 2);
			u4.Street = "467 Nueces St.";
			u4.City = "Austin";
			//u4.EmpType = enumUserType."Employee";
			u4.State = State.TX;
			u4.Zip = "78727";
			u4.PhoneNumber = "9074748452";
			u4.Email = "a.taylor@longhorncinema.com";
			u4.UserName = "a.taylor@longhorncinema.com";
			u4.Archived = false;
			var result4 = UserManager.Create(u4, "nostalgic");
			db.SaveChanges();
			u4 = db.Users.FirstOrDefault(u => u.UserName == "a.taylor@longhorncinema.com");
			UserManager.AddToRole(u4.Id, "Employee");
			db.SaveChanges();

			AppUser u5 = new AppUser();
			//u5.Password = "fungus";
			u5.LastName = "Martinez";
			u5.FirstName = "Gregory";
			u5.MiddleInitial = "R";
			u5.Birthday = new DateTime(1992, 3, 30);
			u5.Street = "8295 Sunset Blvd.";
			u5.City = "Austin";
			//u5.EmpType = enumUserType."Employee";
			u5.State = State.TX;
			u5.Zip = "78712";
			u5.PhoneNumber = "9078746718";
			u5.Email = "g.martinez@longhorncinema.com";
			u5.UserName = "g.martinez@longhorncinema.com";
			u5.Archived = false;
			var result5 = UserManager.Create(u5, "fungus");
			db.SaveChanges();
			u5 = db.Users.FirstOrDefault(u => u.UserName == "g.martinez@longhorncinema.com");
			UserManager.AddToRole(u5.Id, "Employee");
			db.SaveChanges();

			AppUser u6 = new AppUser();
			//u6.Password = "longhorns";
			u6.LastName = "Sheffield";
			u6.FirstName = "Martin";
			u6.MiddleInitial = "J";
			u6.Birthday = new DateTime(1996, 12, 29);
			u6.Street = "3886 Avenue A";
			u6.City = "San Marcos";
			//u6.EmpType = enumUserType."Employee";
			u6.State = State.TX;
			u6.Zip = "78666";
			u6.PhoneNumber = "9075479167";
			u6.Email = "m.sheffield@longhorncinema.com";
			u6.UserName = "m.sheffield@longhorncinema.com";
			u6.Archived = false;
			var result6 = UserManager.Create(u6, "longhorns");
			db.SaveChanges();
			u6 = db.Users.FirstOrDefault(u => u.UserName == "m.sheffield@longhorncinema.com");
			UserManager.AddToRole(u6.Id, "Employee");
			db.SaveChanges();

			AppUser u7 = new AppUser();
			//u7.Password = "smitty";
			u7.LastName = "MacLeod";
			u7.FirstName = "Jennifer";
			u7.MiddleInitial = "D";
			u7.Birthday = new DateTime(1997, 6, 10);
			u7.Street = "2504 Far West Blvd.";
			u7.City = "Austin";
			//u7.EmpType = enumUserType."Employee";
			u7.State = State.TX;
			u7.Zip = "78705";
			u7.PhoneNumber = "9074748138";
			u7.Email = "j.macleod@longhorncinema.com";
			u7.UserName = "j.macleod@longhorncinema.com";
			u7.Archived = false;
			var result7 = UserManager.Create(u7, "smitty");
			db.SaveChanges();
			u7 = db.Users.FirstOrDefault(u => u.UserName == "j.macleod@longhorncinema.com");
			UserManager.AddToRole(u7.Id, "Employee");
			db.SaveChanges();

			AppUser u8 = new AppUser();
			//u8.Password = "tanman";
			u8.LastName = "Tanner";
			u8.FirstName = "Jeremy";
			u8.MiddleInitial = "S";
			u8.Birthday = new DateTime(1970, 8, 12);
			u8.Street = "4347 Almstead";
			u8.City = "Austin";
			//u8.EmpType = enumUserType."Employee";
			u8.State = State.TX;
			u8.Zip = "78712";
			u8.PhoneNumber = "9074590929";
			u8.Email = "j.tanner@longhorncinema.com";
			u8.UserName = "j.tanner@longhorncinema.com";
			u8.Archived = false;
			var result8 = UserManager.Create(u8, "tanman");
			db.SaveChanges();
			u8 = db.Users.FirstOrDefault(u => u.UserName == "j.tanner@longhorncinema.com");
			UserManager.AddToRole(u8.Id, "Employee");
			db.SaveChanges();

			AppUser u9 = new AppUser();
			//u9.Password = "countryrhodes";
			u9.LastName = "Rhodes";
			u9.FirstName = "Megan";
			u9.MiddleInitial = "C";
			u9.Birthday = new DateTime(1970, 12, 18);
			u9.Street = "4587 Enfield Rd.";
			u9.City = "Austin";
			//u9.EmpType = enumUserType."Employee";
			u9.State = State.TX;
			u9.Zip = "78729";
			u9.PhoneNumber = "9073744746";
			u9.Email = "m.rhodes@longhorncinema.com";
			u9.UserName = "m.rhodes@longhorncinema.com";
			u9.Archived = false;
			var result9 = UserManager.Create(u9, "countryrhodes");
			db.SaveChanges();
			u9 = db.Users.FirstOrDefault(u => u.UserName == "m.rhodes@longhorncinema.com");
			UserManager.AddToRole(u9.Id, "Employee");
			db.SaveChanges();

			AppUser u10 = new AppUser();
			//u10.Password = "stewboy";
			u10.LastName = "Stuart";
			u10.FirstName = "Eric";
			u10.MiddleInitial = "F";
			u10.Birthday = new DateTime(1971, 3, 11);
			u10.Street = "5576 Toro Ring";
			u10.City = "Austin";
			//u10.EmpType = enumUserType."Employee";
			u10.State = State.TX;
			u10.Zip = "78758";
			u10.PhoneNumber = "9078178335";
			u10.Email = "e.stuart@longhorncinema.com";
			u10.UserName = "e.stuart@longhorncinema.com";
			u10.Archived = false;
			var result10 = UserManager.Create(u10, "stewboy");
			db.SaveChanges();
			u10 = db.Users.FirstOrDefault(u => u.UserName == "e.stuart@longhorncinema.com");
			UserManager.AddToRole(u10.Id, "Employee");
			db.SaveChanges();

			AppUser u11 = new AppUser();
			//u11.Password = "squirrel";
			u11.LastName = "Miller";
			u11.FirstName = "Charles";
			u11.MiddleInitial = "R";
			u11.Birthday = new DateTime(1972, 7, 20);
			u11.Street = "8962 Main St.";
			u11.City = "Austin";
			//u11.EmpType = enumUserType."Employee";
			u11.State = State.TX;
			u11.Zip = "78709";
			u11.PhoneNumber = "9077458615";
			u11.Email = "c.miller@longhorncinema.com";
			u11.UserName = "c.miller@longhorncinema.com";
			u11.Archived = false;
			var result11 = UserManager.Create(u11, "squirrel");
			db.SaveChanges();
			u11 = db.Users.FirstOrDefault(u => u.UserName == "c.miller@longhorncinema.com");
			UserManager.AddToRole(u11.Id, "Employee");
			db.SaveChanges();

			AppUser u12 = new AppUser();
			//u12.Password = "swansong";
			u12.LastName = "Taylor";
			u12.FirstName = "Rachel";
			u12.MiddleInitial = "O";
			u12.Birthday = new DateTime(1972, 12, 20);
			u12.Street = "345 Longview Dr.";
			u12.City = "Austin";
			//u12.EmpType = enumUserType."Manager";
			u12.State = State.TX;
			u12.Zip = "78746";
			u12.PhoneNumber = "9074512631";
			u12.Email = "r.taylor@longhorncinema.com";
			u12.UserName = "r.taylor@longhorncinema.com";
			u12.Archived = false;
			var result12 = UserManager.Create(u12, "swansong");
			db.SaveChanges();
			u12 = db.Users.FirstOrDefault(u => u.UserName == "r.taylor@longhorncinema.com");
			UserManager.AddToRole(u12.Id, "Manager");
			db.SaveChanges();

			AppUser u13 = new AppUser();
			//u13.Password = "lottery";
			u13.LastName = "Lawrence";
			u13.FirstName = "Victoria";
			u13.MiddleInitial = "Y";
			u13.Birthday = new DateTime(1973, 4, 28);
			u13.Street = "6639 Butterfly Ln.";
			u13.City = "Austin";
			//u13.EmpType = enumUserType."Employee";
			u13.State = State.TX;
			u13.Zip = "78712";
			u13.PhoneNumber = "9079457399";
			u13.Email = "v.lawrence@longhorncinema.com";
			u13.UserName = "v.lawrence@longhorncinema.com";
			u13.Archived = false;
			var result13 = UserManager.Create(u13, "lottery");
			db.SaveChanges();
			u13 = db.Users.FirstOrDefault(u => u.UserName == "v.lawrence@longhorncinema.com");
			UserManager.AddToRole(u13.Id, "Employee");
			db.SaveChanges();

			AppUser u14 = new AppUser();
			//u14.Password = "evanescent";
			u14.LastName = "Rogers";
			u14.FirstName = "Allen";
			u14.MiddleInitial = "H";
			u14.Birthday = new DateTime(1978, 6, 21);
			u14.Street = "4965 Oak Hill";
			u14.City = "Austin";
			//u14.EmpType = enumUserType."Manager";
			u14.State = State.TX;
			u14.Zip = "78705";
			u14.PhoneNumber = "9078752943";
			u14.Email = "a.rogers@longhorncinema.com";
			u14.UserName = "a.rogers@longhorncinema.com";
			u14.Archived = false;
			var result14 = UserManager.Create(u14, "evanescent");
			db.SaveChanges();
			u14 = db.Users.FirstOrDefault(u => u.UserName == "a.rogers@longhorncinema.com");
			UserManager.AddToRole(u14.Id, "Manager");
			db.SaveChanges();

			AppUser u15 = new AppUser();
			//u15.Password = "monty3";
			u15.LastName = "Markham";
			u15.FirstName = "Elizabeth";
			u15.MiddleInitial = "K";
			u15.Birthday = new DateTime(1990, 5, 21);
			u15.Street = "7861 Chevy Chase";
			u15.City = "Austin";
			//u15.EmpType = enumUserType."Employee";
			u15.State = State.TX;
			u15.Zip = "78785";
			u15.PhoneNumber = "9074579845";
			u15.Email = "e.markham@longhorncinema.com";
			u15.UserName = "e.markham@longhorncinema.com";
			u15.Archived = false;
			var result15 = UserManager.Create(u15, "monty3");
			db.SaveChanges();
			u15 = db.Users.FirstOrDefault(u => u.UserName == "e.markham@longhorncinema.com");
			UserManager.AddToRole(u15.Id, "Employee");
			db.SaveChanges();

			AppUser u16 = new AppUser();
			//u16.Password = "hecktour";
			u16.LastName = "Baker";
			u16.FirstName = "Christopher";
			u16.MiddleInitial = "E";
			u16.Birthday = new DateTime(1993, 3, 16);
			u16.Street = "1245 Lake Anchorage Blvd.";
			u16.City = "Cedar Park";
			//u16.EmpType = enumUserType."Employee";
			u16.State = State.TX;
			u16.Zip = "78613";
			u16.PhoneNumber = "9075571146";
			u16.Email = "c.baker@longhorncinema.com";
			u16.UserName = "c.baker@longhorncinema.com";
			u16.Archived = false;
			var result16 = UserManager.Create(u16, "hecktour");
			db.SaveChanges();
			u16 = db.Users.FirstOrDefault(u => u.UserName == "c.baker@longhorncinema.com");
			UserManager.AddToRole(u16.Id, "Employee");
			db.SaveChanges();

			AppUser u17 = new AppUser();
			//u17.Password = "rankmary";
			u17.LastName = "Saunders";
			u17.FirstName = "Sarah";
			u17.MiddleInitial = "M";
			u17.Birthday = new DateTime(1997, 1, 5);
			u17.Street = "332 Avenue C";
			u17.City = "Austin";
			//u17.EmpType = enumUserType."Employee";
			u17.State = State.TX;
			u17.Zip = "78733";
			u17.PhoneNumber = "9073497810";
			u17.Email = "s.saunders@longhorncinema.com";
			u17.UserName = "s.saunders@longhorncinema.com";
			u17.Archived = false;
			var result17 = UserManager.Create(u17, "rankmary");
			db.SaveChanges();
			u17 = db.Users.FirstOrDefault(u => u.UserName == "s.saunders@longhorncinema.com");
			UserManager.AddToRole(u17.Id, "Employee");
			db.SaveChanges();

			AppUser u18 = new AppUser();
			//u18.Password = "walkamile";
			u18.LastName = "Sewell";
			u18.FirstName = "William";
			u18.MiddleInitial = "G";
			u18.Birthday = new DateTime(1986, 5, 25);
			u18.Street = "2365 51st St.";
			u18.City = "Austin";
			//u18.EmpType = enumUserType."Manager";
			u18.State = State.TX;
			u18.Zip = "78755";
			u18.PhoneNumber = "9074510084";
			u18.Email = "w.sewell@longhorncinema.com";
			u18.UserName = "w.sewell@longhorncinema.com";
			u18.Archived = false;
			var result18 = UserManager.Create(u18, "walkamile");
			db.SaveChanges();
			u18 = db.Users.FirstOrDefault(u => u.UserName == "w.sewell@longhorncinema.com");
			UserManager.AddToRole(u18.Id, "Manager");
			db.SaveChanges();

			AppUser u19 = new AppUser();
			//u19.Password = "changalang";
			u19.LastName = "Mason";
			u19.FirstName = "Jack";
			u19.MiddleInitial = "L";
			u19.Birthday = new DateTime(1986, 6, 6);
			u19.Street = "444 45th St";
			u19.City = "Austin";
			//u19.EmpType = enumUserType."Employee";
			u19.State = State.TX;
			u19.Zip = "78701";
			u19.PhoneNumber = "9018833432";
			u19.Email = "j.mason@longhorncinema.com";
			u19.UserName = "j.mason@longhorncinema.com";
			u19.Archived = false;
			var result19 = UserManager.Create(u19, "changalang");
			db.SaveChanges();
			u19 = db.Users.FirstOrDefault(u => u.UserName == "j.mason@longhorncinema.com");
			UserManager.AddToRole(u19.Id, "Employee");
			db.SaveChanges();

			AppUser u20 = new AppUser();
			//u20.Password = "offbeat";
			u20.LastName = "Jackson";
			u20.FirstName = "Jack";
			u20.MiddleInitial = "J";
			u20.Birthday = new DateTime(1986, 10, 16);
			u20.Street = "222 Main";
			u20.City = "Austin";
			//u20.EmpType = enumUserType."Employee";
			u20.State = State.TX;
			u20.Zip = "78760";
			u20.PhoneNumber = "9075554545";
			u20.Email = "j.jackson@longhorncinema.com";
			u20.UserName = "j.jackson@longhorncinema.com";
			u20.Archived = false;
			var result20 = UserManager.Create(u20, "offbeat");
			db.SaveChanges();
			u20 = db.Users.FirstOrDefault(u => u.UserName == "j.jackson@longhorncinema.com");
			UserManager.AddToRole(u20.Id, "Employee");
			db.SaveChanges();

			AppUser u21 = new AppUser();
			//u21.Password = "landus";
			u21.LastName = "Nguyen";
			u21.FirstName = "Mary";
			u21.MiddleInitial = "J";
			u21.Birthday = new DateTime(1988, 4, 5);
			u21.Street = "465 N. Bear Cub";
			u21.City = "Austin";
			//u21.EmpType = enumUserType."Employee";
			u21.State = State.TX;
			u21.Zip = "78734";
			u21.PhoneNumber = "9075524141";
			u21.Email = "m.nguyen@longhorncinema.com";
			u21.UserName = "m.nguyen@longhorncinema.com";
			u21.Archived = false;
			var result21 = UserManager.Create(u21, "landus");
			db.SaveChanges();
			u21 = db.Users.FirstOrDefault(u => u.UserName == "m.nguyen@longhorncinema.com");
			UserManager.AddToRole(u21.Id, "Employee");
			db.SaveChanges();

			AppUser u22 = new AppUser();
			//u22.Password = "rhythm";
			u22.LastName = "Barnes";
			u22.FirstName = "Susan";
			u22.MiddleInitial = "M";
			u22.Birthday = new DateTime(1993, 2, 22);
			u22.Street = "888 S. Main";
			u22.City = "Kyle";
			//u22.EmpType = enumUserType."Employee";
			u22.State = State.TX;
			u22.Zip = "78640";
			u22.PhoneNumber = "9556662323";
			u22.Email = "s.barnes@longhorncinema.com";
			u22.UserName = "s.barnes@longhorncinema.com";
			u22.Archived = false;
			var result22 = UserManager.Create(u22, "rhythm");
			db.SaveChanges();
			u22 = db.Users.FirstOrDefault(u => u.UserName == "s.barnes@longhorncinema.com");
			UserManager.AddToRole(u22.Id, "Employee");
			db.SaveChanges();

			AppUser u23 = new AppUser();
			//u23.Password = "kindly";
			u23.LastName = "Jones";
			u23.FirstName = "Lester";
			u23.MiddleInitial = "L";
			u23.Birthday = new DateTime(1996, 6, 29);
			u23.Street = "999 LeBlat";
			u23.City = "Austin";
			//u23.EmpType = enumUserType."Employee";
			u23.State = State.TX;
			u23.Zip = "78747";
			u23.PhoneNumber = "9886662222";
			u23.Email = "l.jones@longhorncinema.com";
			u23.UserName = "l.jones@longhorncinema.com";
			u23.Archived = false;
			var result23 = UserManager.Create(u23, "kindly");
			db.SaveChanges();
			u23 = db.Users.FirstOrDefault(u => u.UserName == "l.jones@longhorncinema.com");
			UserManager.AddToRole(u23.Id, "Employee");
			db.SaveChanges();

			AppUser u24 = new AppUser();
			//u24.Password = "instrument";
			u24.LastName = "Garcia";
			u24.FirstName = "Hector";
			u24.MiddleInitial = "W";
			u24.Birthday = new DateTime(1997, 5, 13);
			u24.Street = "777 PBR Drive";
			u24.City = "Austin";
			//u24.EmpType = enumUserType."Employee";
			u24.State = State.TX;
			u24.Zip = "78712";
			u24.PhoneNumber = "9221114444";
			u24.Email = "h.garcia@longhorncinema.com";
			u24.UserName = "h.garcia@longhorncinema.com";
			u24.Archived = false;
			var result24 = UserManager.Create(u24, "instrument");
			db.SaveChanges();
			u24 = db.Users.FirstOrDefault(u => u.UserName == "h.garcia@longhorncinema.com");
			UserManager.AddToRole(u24.Id, "Employee");
			db.SaveChanges();

			AppUser u25 = new AppUser();
			//u25.Password = "arched";
			u25.LastName = "Silva";
			u25.FirstName = "Cindy";
			u25.MiddleInitial = "S";
			u25.Birthday = new DateTime(1997, 12, 29);
			u25.Street = "900 4th St";
			u25.City = "Austin";
			//u25.EmpType = enumUserType."Employee";
			u25.State = State.TX;
			u25.Zip = "78758";
			u25.PhoneNumber = "9221113333";
			u25.Email = "c.silva@longhorncinema.com";
			u25.UserName = "c.silva@longhorncinema.com";
			u25.Archived = false;
			var result25 = UserManager.Create(u25, "arched");
			db.SaveChanges();
			u25 = db.Users.FirstOrDefault(u => u.UserName == "c.silva@longhorncinema.com");
			UserManager.AddToRole(u25.Id, "Employee");
			db.SaveChanges();

			AppUser u26 = new AppUser();
			//u26.Password = "median";
			u26.LastName = "Lopez";
			u26.FirstName = "Marshall";
			u26.MiddleInitial = "T";
			u26.Birthday = new DateTime(1996, 11, 4);
			u26.Street = "90 SW North St";
			u26.City = "Austin";
			//u26.EmpType = enumUserType."Employee";
			u26.State = State.TX;
			u26.Zip = "78729";
			u26.PhoneNumber = "9234442222";
			u26.Email = "m.lopez@longhorncinema.com";
			u26.UserName = "m.lopez@longhorncinema.com";
			u26.Archived = false;
			var result26 = UserManager.Create(u26, "median");
			db.SaveChanges();
			u26 = db.Users.FirstOrDefault(u => u.UserName == "m.lopez@longhorncinema.com");
			UserManager.AddToRole(u26.Id, "Employee");
			db.SaveChanges();

			AppUser u27 = new AppUser();
			//u27.Password = "approval";
			u27.LastName = "Larson";
			u27.FirstName = "Bill";
			u27.MiddleInitial = "B";
			u27.Birthday = new DateTime(1999, 11, 14);
			u27.Street = "1212 N. First Ave";
			u27.City = "Round Rock";
			//u27.EmpType = enumUserType."Employee";
			u27.State = State.TX;
			u27.Zip = "78665";
			u27.PhoneNumber = "9795554444";
			u27.Email = "b.larson@longhorncinema.com";
			u27.UserName = "b.larson@longhorncinema.com";
			u27.Archived = false;
			var result27 = UserManager.Create(u27, "approval");
			db.SaveChanges();
			u27 = db.Users.FirstOrDefault(u => u.UserName == "b.larson@longhorncinema.com");
			UserManager.AddToRole(u27.Id, "Employee");
			db.SaveChanges();

			AppUser u28 = new AppUser();
			//u28.Password = "decorate";
			u28.LastName = "Rankin";
			u28.FirstName = "Suzie";
			u28.MiddleInitial = "R";
			u28.Birthday = new DateTime(1999, 12, 17);
			u28.Street = "23 Polar Bear Road";
			u28.City = "Austin";
			//u28.EmpType = enumUserType."Employee";
			u28.State = State.TX;
			u28.Zip = "78712";
			u28.PhoneNumber = "9893336666";
			u28.Email = "s.rankin@longhorncinema.com";
			u28.UserName = "s.rankin@longhorncinema.com";
			u28.Archived = false;
			var result28 = UserManager.Create(u28, "decorate");
			db.SaveChanges();
			u28 = db.Users.FirstOrDefault(u => u.UserName == "s.rankin@longhorncinema.com");
			UserManager.AddToRole(u28.Id, "Employee");
			db.SaveChanges();

		}
	}
}
